### ISSUE TITLE
Fix for: "Araq's Musings - Araq's (Nim creator) personal blog on nim"

### ISSUE THREAD

**Issue by da99** [VPashkov/awesome-nim#21]
The current url: http://nim-lang.org/blog/ (403 Forbidden)
The updated url is: http://nim-lang.org/blog.html

**Comment by vpashkov** [comment]
Fixed. Thank you!

**Comment by dom96** [comment]
Nope. That's now the official Nim blog. Araq's musings are gone.

**Comment by vpashkov** [comment]
Oh I see. It is better now?

**Comment by dom96** [comment]
Yep, looks good :)
