### ISSUE TITLE
Nim for Embedded

### ISSUE THREAD

**Issue by mratsim** [VPashkov/awesome-nim#33]
Embedded questions are recurring in the forum and IRC/Gitter.

As a start MSP430
 - https://github.com/lonetech/nim-msp430
 - https://gitlab.com/jalexander8717/msp430f5510-nim

Nim on STM32F3
 - https://github.com/mwbrown/nim_stm32f3

Nim Arduino
 - https://github.com/gokr/ardunimo

I'm pretty sure @federicoceratto has some related repos as well

**Comment by vpashkov** [comment]
Great idea. 
I think we need a new category "Embedded" with all those projects.
@mratsim, would you like to make a PR?

**Comment by FedericoCeratto** [comment]
We are tracking needed libraries & tools on https://github.com/nim-lang/needed-libraries/issues/84
