### ISSUE TITLE
REPLs?

### ISSUE THREAD

**Issue by jabbalaci** [VPashkov/awesome-nim#52]
Are there any good REPLs for Nim? I tried [nrpl](https://github.com/wheineman/nrpl) and [tnim](https://github.com/jlp765/tnim) but they are quite simple.

Update: [INim](https://github.com/AndreiRegiani/INim) seems good.

**Comment by vpashkov** [comment]
INim looks interesting indeed.
Added it to this repo.

**Comment by jabbalaci** [comment]
Awesome! Thanks.
